### ISSUE TITLE
Tracker: Tech Debt

### ISSUE THREAD

**Issue by ibgreen** [visgl/deck.gl#1668]
## View Classes Tech Debt

Tech debt remaining from [View Classes RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v6.0/view-class-rfc.md)

Our View State system is powerful but too complex and confusing, we need to actively identify weak issues in the design and current implementation.

### v7.x? Design Issues

 - [ ] First person view - move `modelMatrix` to `viewState`?
 - [ ] Silent failures if `modelMatrix` is not provided? 

### v7.x? Implementation Issues

- [ ] Fix `_activateViewport` (avoid unnecessary activation)
- [ ] Better deep equal, limit regeneration of viewports
- [ ] Tests (check getViewport for each subclass)
- [ ] Tests (check getViewport for each subclass)

Transition support for different `viewState` shapes:
- [ ] Move `extractViewState` to `View` or `Viewport` (currently `MapView` specific).

### v6.0

- [x] Move `ViewManager` out of `LayerManager` #1926 
- [x] Don't track width/height in viewState See #1764
- [x] Remove deprecated viewports

**Comment by tgorkin** [comment]
@ibgreen consolidate with #2199
