### ISSUE TITLE
Tracker: Trip Layer

### ISSUE THREAD

**Issue by ibgreen** [visgl/deck.gl#2523]
Tracking issues/feature requests in the trip layer

- [x] Adding interactivity or pickable functionality #2467
- [ ] Trip Routes Performance Issues #2186
- [ ] Trips won't show up when the timestamp value is large #2397
- [x] TripsLayer - how can I use it without react? #2425
- [ ] Timestamp in Trips Layer trips.json segments #1854
- [x] Use trips layer standalone #1916
- [x] Enable stroke width setting for trips-layer #1624
- [ ] Popup is not interactive in combination with trips example #1855
- [x] Changing line width in the trips example: not working #1331

**Comment by scraly** [comment]
Any news about "Enable stroke width setting for trips-layer #1624" enh/issue? Thx.

**Comment by Kyngo** [comment]
What about #1331 or #1624 ? Looks like nobody is answering in here.

**Comment by ibgreen** [comment]
This is implemented in deck.gl v7 which is in the final stages of release preparation.

For the "adventurous", there is a release candidate published on npm: 7.0.0-rc.1

**Comment by markcarroll** [comment]
Having to build the trips layer each frame of the animation loop is killing CPU.  Is there a way to move the animation into the GPU or somewhere so it is not having to rebuild the array each time?

**Comment by ibgreen** [comment]
> Having to build the trips layer each frame of the animation loop is killing CPU. Is there a way to move the animation into the GPU or somewhere so it is not having to rebuild the array each time?

For `TripsLayer` the animation is done in the GPU based on the time. Creating a new TripsLayer instance with an updated time prop is not expensive, as long as the other props don't change values.

You are likely providing a new `data` array (maybe just an identical copy, instead of the same array as previous render, but that is enough to trigger deck.gl updates) You only want to update your data array when your data actually changes.

Set `deck.log.priority` to values between 1 and 4 in your debugger console to help trace your updates.
