### ISSUE TITLE
Tracker: Data Loading Enhancements

### ISSUE THREAD

**Issue by ibgreen** [visgl/deck.gl#3072]
Features to improve data loading support:

deck.gl 7.2
- [x] Support for loaders.gl `parse` method in layer URL/Promise loading
- [x] Support `onDataLoaded` callback for layer URL/Promise loading
- [x] Support loaders.gl geometry in PointCloud

deck.gl v?
- [ ] Real-Time Data Support RFC #3073 
- [x] New `loading data` Developer Guide article
- [x] Enhance binary support to accepts loaders.gl geometry?
