### ISSUE TITLE
Tracker: Playground (aka JSON browser)

### ISSUE THREAD

**Issue by ibgreen** [visgl/deck.gl#3580]
This is a tracker for the Playground and core JSON API integration. Also see:
- #3079 Tracker: JSON/Python API enhancements
- #3557 Tracker: @deck.gl.json as generic component wrapping solution

### 7.4+ 

- [x] Update JSON examples to use tooltip functionality
- [ ] Implement string template syntax in expression eval?
- [x] Implement function syntax, e.g. `@=...` to avoid need for prop types?
- [ ] JSON playground interpreting some layer parameters as variables #3948 
- [x] Change `type` key to something less common `@type` or `@@type`?
- [ ] Error handling, ensure exceptions don't break browser and messages are plumbed through to UI.
- [ ] probe Log integration
- [ ] Local storage of JSON edits in playground, reload button.

### 7.3 

See unresolved comments in #3577.

- [x] Use loaders.gl/csv+json instead of `enhancedFetch`
- [x] Remove AutoSize from DeckGL in Playground
- [x] Remove function/prop type logic from Playground
- [x] Add Playground to website as external link
- [x] Make Playground buildable as part of website
- [x] Build Playground as a pure `JSONConfiguration` on the stock `JSONConverter`
- [x] Refactor @deck.gl/json to not be deck dependent
- [x] Rename `JSON browser` to `Playground`
