### ISSUE TITLE
Tracker: Ocular-Gatsby Website Upgrade

### ISSUE THREAD

**Issue by tgorkin** [visgl/deck.gl#3754]
#### Target Use case
We should upgrade the deck.gl documentation and examples website to take advantage of:
- Better SEO - doc pages and examples should appear at or near top of results for relevant google searches
- Embedded search - developers should be able to effectively search keywords in deck.gl doc pages 
- Styling update - fonts, layout, styling should be updated to be consistent with latest vis.gl UI standards (see [loaders.gl](https://loaders.gl/) and [luma.gl](https://luma.gl)).  

#### Proposed feature
Switch deck.gl's website over to the latest [Ocular gatsby based website system](https://uber-web.github.io/).  

Preliminary staged version of site - [https://tgorkin.github.io/](https://tgorkin.github.io/)

#### V8.1
- [ ] Upgrade to ocular-gatsby 1.0.6 (uses gatsby themes)
- [ ] Add interactive demo back to hero page #3774
- [ ] Add gallery back to website
- [ ] Add JSON playground back to website
- [ ] Interactive examples embedded in layer API doc pages #3855
- [ ] Add showcase page to ocular gatsby
- [ ] Update doc pages table of contents to include newly added/missing pages
- [ ] All internal doc links not working
- [ ] Mangled page titles in TOC (see API Reference - Layer and Views)
- [ ] Styling, imagary, and Uber branding on main page regressed
- [ ] Cannot type in search bar (Firefox only)
- [ ] Missing developer survey
- [ ] Missing tooltips on control panels in examples

#### V8.0
- [x] Bring ib/gatsby-website-initial branch up to date with latest master #3755 
- [x] Build and stage a preliminary version of ocular-gatsby site #3756
- [x] Test preliminary version of ocular-gatsby and catalog all errors and issues #3757 
- [ ] Add examples back to website #3775

Ocular issues
- [ ] Scrolling is limited in TOC when fully expanded 
- [ ] Missing content warnings in console
- [ ] Font styling in Safari falling back to Times New Roman
- [ ] Examples TOC not showing all entries
- [ ] Extra padding on layout container around examples

Open questions
- Embedded examples in documentation pages? 
- mdx - react-like jsx code in markdown, gatsby plugin, still issues that need work
- JSON browser
- gallery examples - https://deck.gl/showcases/gallery/

#### To Do List 
  - [x] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Moving to #4717
