### ISSUE TITLE
pydeck 0.3.0 Release Tracker

### ISSUE THREAD

**Issue by ajduberstein** [visgl/deck.gl#4103]
For #3640 

Coincides with deck.gl 8.1 release (mid-February 2020)

#### Publication checklist
- [X] Release pydeck 0.3.0 to PyPI
- [X] Release new documentation page (https://pydeck.gl)
- [x] Update mybinder.org examples
- [x] Release pydeck 0.3.0 on conda-forge (see https://github.com/conda-forge/pydeck-feedstock/pull/2)
- [ ] Update docs (in this case, RTD stable should route to https://pydeck.gl and latest can simply build)
- [x] Get RTD _latest_ docs gallery working (https://readthedocs.org/projects/deckgl/builds/). This supports the documentation build badge and gives us a staging page.

#### Planned updates
- [x] Supporting streaming binary bidirectionally from Jupyter to its frontend - supported by #4167 and #4169
- [x] Creating a page like https://deck.gl/gallery/ for pydeck
- [x] Make @jupyter-widget/base, a dependency for @deck.gl/jupyter-widget, an external – verified to work in 8.1.0-alpha.0.
- [x] Anaconda conda-forge publication, in #4202

#### Tentative updates
- [x] Dynamic registration for custom layers as specified in #4090
- [ ] Support for the [data filter extension](https://github.com/uber/deck.gl/blob/master/docs/api-reference/extensions/data-filter-extension.md).

**Comment by ibgreen** [comment]
Can we add #4090 as tentative?
