### ISSUE TITLE
Tracker: Geospatial data handling improvements

### ISSUE THREAD

**Issue by Pessimistress** [visgl/deck.gl#4104]
- [x] Offer the option to split features at the 180 meridian
- [x] Repeat maps at low zoom levels
- [ ] Fixed frame coordinates
- [x] Globe view
- [ ] Alternative 2D projections
