### ISSUE TITLE
pydeck: 0.4.0 release tracker

### ISSUE THREAD

**Issue by ajduberstein** [visgl/deck.gl#4323]
For #3640

Planned updates
- [x] JupyterLab >= 2.0 integration (#4488)
- [x] Notebook/Lab integration tests in CI

Tentative updates

- [ ] Update tooltip to use @deck.gl/json
- [x] Provide a standalone HTML file that doesn't need internet (#4290)
- [x] Google Maps base maps (#4632)
- [ ] Deeper widget binding with pydeck visualization objects (#4511)
- [ ] Support multiple map views, as in the second deck.gl/playground HexagonLayer example

**Comment by ajduberstein** [comment]
#4818, released here: https://pypi.org/project/pydeck/0.4.0/
