### ISSUE TITLE
Tracker: Data Manager

### ISSUE THREAD

**Issue by Pessimistress** [visgl/deck.gl#4620]
[RFC](https://github.com/visgl/deck.gl/blob/master/dev-docs/RFCs/proposals/data-manager-rfc.md)

#### To Do List
  - [x] Add label and assign to milestone
  - [x] DataManager class implementation
  - [x] Replace per-layer async prop loading with DataManager
  - [x] Experimental Deck API
  - [ ] Doc update
  - [ ] What’s new update
  - [ ] Test
