### ISSUE TITLE
Tracker: Globe Projection

### ISSUE THREAD

**Issue by Pessimistress** [visgl/deck.gl#4638]
### Target use case

Visualize the earth as a 3D globe.

Early prep work was done in v8.0, see backgrounds in [projection system expansion RFC](https://github.com/visgl/deck.gl/blob/master/dev-docs/RFCs/v8.0/projection-system-expansion-rfc.md)

### Proposed feature

If the user swaps out the default `MapView` with a `GlobeView`, deck will project geospatial data onto a 3D globe instead of a Web Mercator map:

```js
const {GlobeView} from '@deck.gl/core';

new Deck({
  views: new GlobeView(),
  layers: [
    new GeoJsonLayer(...)
  ]
});
```

### New public-facing APIs

- New Viewport class `GlobeViewport`, initially experimental
- New View class `GlobeView`, initially experimental
- New Controller class `GlobeController` (light extension of `MapController`), initially experimental
- A new `project` module function `mat3 project_getOrientationMatrix(vec3 up)`, which returns a matrix that transforms a vec3 from `up: [0, 0, 1]` (the default common space) to align with the provided `up`.

#### To Do List 
  - [x] Add label and assign to milestone
  - [x] Core module: View classes
  - [x] Core module: project module changes
  - [x] Layers catalog: handle the new projection mode
  - [x] Doc update
  - [x] What’s new update
  - [ ] Test

**Comment by Pessimistress** [comment]
Layer-level complications:

#### ArcLayer

The core `ArcLayer` is designed to only work in Web Mercator projection. My proposed solution is to merge `GreatCircleLayer` into `ArcLayer` (these two shaders already overlap significantly) and can be turned on with the prop `greatCircle: true`. Then we can force switch to using great circle in globe projection mode.

#### PathLayer

A long straight path (e.g. `[[0, 0], [90, 0]]`) may have to be broken up into finer-grain segments to conform to the surface of the earth. This requires `cutPolylineByGrid` from `@math.gl/polygon`, which will be performed automatically if the PathLayer is rendered into a `GlobeViewport`.

One concern is that this will bloat the dependency of `PathLayer`. One way to mitigate this is to introduce a private API on the `Viewport` class (e.g. `viewport.preprojectPath`) which will move the dependency into the `GlobeViewport` class.

#### SolidPolygonLayer

Similar to the issue above, a big polygon may have to be broken up to project correctly. This can be done with the `cutPolygonByGrid` utility from `@math.gl/polygon`.

The layer will also need to mark the cut lines as invalid so that no sides are rendered for them in extruded mode.

**Comment by kylebarron** [comment]
In a couple sentences, what's the `TileLayer` complication? Mapping web mercator positions onto globe positions? You can't just project the positions of that mercator square into globe positions?

**Comment by Pessimistress** [comment]
#### TileLayer

- The OSM tile traversal naturally only works with Web Mercator projection. A naive fix is to construct a WebMercatorViewport from the GlobeViewport's bounding box.
- TerrainLayer and MVTLayer use the cartesian coordinate system (preprojected WebMercator coordinates). The project shader module need to implement a conversion from WebMercator coordinates to the global common space (z<12) and project-uniforms need to produce the correct `unitsPerWorldUnit` scale (z>=12).
- The ClipExtension's fragment version (used on PathLayer and SolidPolygonLayer) relies on the assumption that the world is flat. I'm open to suggestions on how this can be handled efficiently, other than unprojecting back to lngLat coordinates :(

**Comment by ibgreen** [comment]
Thanks for this good writeup, just added my thoughts in case they provide some perspective. If not, no need to defend the current strategy...

> ArcLayer: The core ArcLayer is designed to only work in Web Mercator projection. My proposed solution is to merge GreatCircleLayer into ArcLayer (these two shaders already overlap significantly) and can be turned on with the prop greatCircle: true. Then we can force switch to using great circle in globe projection mode.

- (Assuming I understood this correctly) generally layers should not be designed for a specific projection. Why should a simple arc primitive layer be dependent on Web Mercator projection? Can't we engineer away that limitation? Would that solve the problem. If not, a little curious, how do Great circles replace arcs? They trace a constant distance from the earths center...

> PathLayer: One concern is that this will bloat the dependency of PathLayer. One way to mitigate this is to introduce a private API on the Viewport class (e.g. viewport.preprojectPath) which will move the dependency into the GlobeViewport class.

Gentle vote against that. This stuff is already very complicated. Adding such complications to avoid some dependency makes it worse (unless it is a genuinely useful generalization). The long-term goal must be to build deck into a full 3D supporting engine and set of layers, not a set of add-ons to a flat projection system.

**Comment by Pessimistress** [comment]
> Why should a simple arc primitive layer be dependent on Web Mercator projection? Can't we engineer away that limitation?

The ArcLayer raises an arc over the straight line connecting source and target on the XY plane. So technically it supports any projection where "up" is always [0, 0, 1].

In the globe case, that "straight line" should be along the surface of the earth, i.e. the great circle.

![image](https://user-images.githubusercontent.com/2059298/83699043-e5ba2000-a5b7-11ea-9e15-ffda6ce094ff.png)

**Comment by ibgreen** [comment]
Ok thanks, it is not dependent on web mercator as such, it works in all our non-globe projections. That is what I was assuming.

I can see how adjusting the "ground points" to the sphere (and make sure we have enough of them to follow the globe's curvature) becomes a main problem for all our layers. And with support for elevation offsets this will need to be even more flexible, so might as well start generalizing it now.

Not opposed to merging those two layers, the GreatCircleLayer always seemed a bit specialized.

PS Those are some neat little images, how do you make them?

**Comment by Pessimistress** [comment]
> I can see how adjusting the "ground points" to the sphere (and make sure we have enough of them to follow the globe's curvature) becomes a main problem for all our layers. 

You can find the general solution to adding z to a ground point in https://github.com/visgl/deck.gl/pull/4640. The ground point is usually provided by the user. The special situation in the ArcLayer's case is that we have to find the ground point by interpolating between two points, and that "interpolation" must be redefined in certain projection systems.

**Comment by ibgreen** [comment]
> You can find the general solution to adding z to a ground point in #4640.

For the completely general case I'd imagine the ground point may need to be sampled from an elevation texture. That has a lot of complications, obviously.

**Comment by Pessimistress** [comment]
That's irrelevant to this issue. Let's not feature creep.

**Comment by ibgreen** [comment]
Ha ha, no I was not suggesting that you add elevation texture support to this PR...

I just prefer to see that big changes we are making are not dead ends that has to be redone or painfully maintained as we then move on towards a more general solution. 

Thus, the fact that you are thinking about general handling of ground points is a very positive thing, and I was more taking the opportunity to hint at what I see would be the longer term direction and see if there were any concerns there.

Ensuring good long term direction is really the main angle from which I review these PRs.

**Comment by grahambates-sp** [comment]
Re : those images above, I just read about a tool that has a similar ability to generate similar diagrams based on mathematical notation.

![image](https://user-images.githubusercontent.com/45166327/83915796-dc71b480-a76b-11ea-8432-dc706b5a22aa.png)

http://penrose.ink/media/Penrose_SIGGRAPH2020.pdf
