### ISSUE TITLE
8.2 Release Tracker

### ISSUE THREAD

**Issue by Pessimistress** [visgl/deck.gl#4717]
Target release date 06/26

- [x] Bump all dependencies (math.gl, probe.gl and loaders.gl) to latest release
- [x] Publish alpha/beta
- [x] Bump all examples to latest alpha/beta
- [x] Stage the website
- [x] Verify whats-new
- [x] Verify upgrade-guide
- [x] Verify all issues in milestone are closed or move out
- [x] Verify all API changes are documented
- [x] Website (docs and example) testing: [staging](http://pessimistress.github.io/deck.gl/#/)
    - [ ] Testing on Chrome
    - [ ] Testing on Safari
    - [ ] Testing on Firefox
    - [ ] Testing on Edge + IE11
    - [ ] Testing on iOS
    - [ ] Testing on Android
- [x] Cut 8.2-release branch after all fixes
- [x] Update website doc urls to point to `8.2-release` branch
- [ ] Publish 8.2 prod version.

**Comment by Pessimistress** [comment]
Website issues:

- [ ] SEO headers contain invalid values

**Comment by ibgreen** [comment]
Just wanted to make sure the results from my test run were captured

- [ ] Blank page on iPhone 11
- [ ] playground example link is back, but is broken
- [ ] Wind example is broken (same on live docs) https://deck.gl/showcases/wind (link to https://philogb.github.io/page/wind/)
- [ ] When navigate to Medium blog, and then back, I loose the header on the deck.gl website
- [ ] I'd love to see a prominent link to pydeck.gl,
- [x] Mandelbrot zoom image broken in https://pessimistress.github.io/deck.gl/docs/developer-guide/64-bits

External
- [ ]  Can we add links to external layers modules? The first example is https://earthengine-layers.com/ which is cool and unique new deck.gl layer.
- [ ] add link to related projects like https://github.com/UnfoldedInc/deck.gl-native somewhere in the docs (It can go into readme/introduction)
- [ ] Roadmap page looks dated. Talks about experimental layers module
- [ ] bitmap-layer example When I click command to tilt pan and then release the mouse, the map occasionally jumps.

P2: 
- [ ] Images in lighting docs have a small "flash" before loading. There are ways to fix it but definitely a P2.
- [ ] examples page no longer has sections (in ToC and thumbnail page)
- [ ] Should the FAQ page also have a link to search the github issues with FAQ tag? We have not been maintaining the FAQ tag, but it is a very easy way to deal with faq issues without republishing the site.

**Comment by Pessimistress** [comment]
> Blank page on iPhone 11

The iOS Safari displays a cached version. You can open the page in private browsing mode to force reload.

**Comment by dcooley** [comment]
In case you're not aware, I've been testing the latest beta releases and the `.min.js` code isn't being minified -  https://unpkg.com/deck.gl@8.2.0-beta.2/dist.min.js. And the `deck.GlobeView()` constructor doesn't exist.

**Comment by Pessimistress** [comment]
It’s experimental (`_GlobeView`): https://github.com/visgl/deck.gl/blob/master/docs/api-reference/globe-view.md

I’ll look into the bundle issue.
