### ISSUE TITLE
Release tracker: pydeck 0.5

### ISSUE THREAD

**Issue by ajduberstein** [visgl/deck.gl#4823]
For #3640

Planned updates

- [x] Richer event handling, like having a click in the UI trigger a Python function (#4848)

Tentative updates (will be in 0.5 or beyond)

- [ ] Add within-browser support for playing data over time
- [ ] Support a selection layer (like nebula.gl's EditableGeoJsonLayer in kepler.gl)
- [ ] End support for Python 2
- [ ] Default stylings
- [ ] Add support for bidirectional Google Colab integration
- [ ] Support feature blending (e.g. dodge and burn blends)
- [ ] Export to image, GIF, and MP4
- [ ] Some form of Kepler <> pydeck integration
- [ ] Add support for a data legend

**Comment by ajduberstein** [comment]
pydeck 0.5.0 is published: [PyPI](https://pypi.org/project/pydeck/0.5.0/)

**Comment by ajduberstein** [comment]
Published to [conda-forge](https://anaconda.org/conda-forge/pydeck).

**Comment by ajduberstein** [comment]
Docs deployed.
