### ISSUE TITLE
8.3 Release Tracker

### ISSUE THREAD

**Issue by Pessimistress** [visgl/deck.gl#4998]
- [x] Bump all dependencies (math.gl, probe.gl and loaders.gl) to latest release
- [x] Publish alpha/beta
- [x] Bump all examples to latest alpha/beta
- [x] Stage the website
- [x] Verify whats-new
- [x] Verify upgrade-guide
- [ ] Verify all issues in milestone are closed or move out
- [x] Verify all API changes are documented
- [x] Website (docs and example) testing: [staging](https://pessimistress.github.io/deck.gl/)
    - [x] Testing on Chrome
    - [x] Testing on Safari
    - [x] Testing on Firefox
    - [ ] Testing on Edge + IE11
    - [x] Testing on iOS
    - [ ] Testing on Android
- [x] Cut 8.3-release branch after all fixes
- [x] Update website doc urls to point to `8.3-release` branch
- [x] Publish 8.3 prod version

**Comment by Pessimistress** [comment]
TODOs re: carto module @alasarr 

- [ ] `/examples/get-started/pure-js/carto` does not work standalone (missing `@deck.gl/carto` dependency)
- [ ] Nice example for the website

**Comment by Pessimistress** [comment]
iOS:

- [ ] HeatmapLayer example all back
- [ ] ScreenGridLayer example not rendered
