### ISSUE TITLE
pydeck 0.6 Release Tracker

### ISSUE THREAD

**Issue by ajduberstein** [visgl/deck.gl#5063]
Tentative updates

- [x] Move to a Carto base map (Handled in #5131)
- [x] Utilities for loading local images into deck (for #5121, #4625) (PR #5162)
- [x] Add Carto layer examples
- [x] End support for Python 2
- [ ] Add support for bidirectional Google Colab integration
- [ ] Add within-browser support for playing data over time
- [ ] Support a selection layer (like nebula.gl's EditableGeoJsonLayer in kepler.gl)
- [ ] Default stylings
- [ ] Support feature blending (e.g. dodge and burn blends)
- [ ] Export to image, GIF, and MP4
- [ ] Some form of Kepler <> pydeck integration
- [ ] Add support for a data legend (#4851)
- [ ] Display message if widget is not enabled

**Comment by ibgreen** [comment]
There is a bunch of open PRs, work through those as well? E.g.
- [ ] #4096
- [ ] #4897
... 

Happy to help here.
