### ISSUE TITLE
Controller Feature Requests Tracker

### ISSUE THREAD

**Issue by Pessimistress** [visgl/deck.gl#5089]
- [x] Three finger swipe to change pitch
- [x] Expose EventManager options e.g. click delay
- [ ] Add callback for immediate click
- [x] Expose more controller options, e.g. keyboard navigation speed, invert pan
- [x] Inertia for scroll zoom and panning
- [x] Add callback for interaction state

**Comment by Foosmate** [comment]
A 3-finger swipe for tilting is not a good solution since 99% of all other touch interfaces use 2-finger swipe for tilting. In other words most users will not find this new feature since everybody expects "common behaviour" for this gesture.

**Comment by euzu** [comment]
First of all, thank you for including the pitch/tilt gesture. But normally every user knows it with two fingers. Why was a new gesture with three fingers used in this case? Is it possible to activate it with a two finger gesture?

**Comment by euzu** [comment]
There is another problem with three finger swipe gesture. On my android mobilephone it is recognized as splitscreen gesture and not forwarded to the browser
