### ISSUE TITLE
8.4 Release Tracker

### ISSUE THREAD

**Issue by Pessimistress** [visgl/deck.gl#5373]
Target release date 01/31

- [x] Bump all dependencies (luma.gl, math.gl, probe.gl and loaders.gl) to latest release
- [x] Publish alpha/beta
- [x] Bump all examples to latest alpha/beta
- [x] Stage the website
- [x] Verify whats-new
- [x] Verify upgrade-guide
- [x] Verify all issues in milestone are closed or move out
- [x] Verify all API changes are documented
- [x] Website (docs and example) testing: [staging](https://pessimistress.github.io/deck.gl/)
    - [x] Testing on Chrome
    - [x] Testing on Safari
    - [x] Testing on Firefox
    - [x] Testing on Edge + IE11
    - [x] Testing on iOS
    - [x] Testing on Android
- [x] Cut 8.4-release branch after all fixes
- [x] Update website doc urls to point to `8.4-release` branch
- [x] Publish 8.4 prod version.

**Comment by kylebarron** [comment]
> 06/26

You mean `01/26`? 😄

**Comment by Pessimistress** [comment]
- [ ] GlobeView example is broken in Safari (date parsing error)
