### ISSUE TITLE
pydeck 0.7 Release Tracker

### ISSUE THREAD

**Issue by ajduberstein** [visgl/deck.gl#5514]
#### Updates

- [ ] Support for TileLayer

#### Tentative updates

- [ ] Add support for bidirectional Google Colab integration
- [ ] Add within-browser support for playing data over time
- [ ] Support a selection layer (like nebula.gl's EditableGeoJsonLayer in kepler.gl)
- [ ] Default stylings
- [ ] Support feature blending (e.g. dodge and burn blends)
- [ ] Export to image, GIF, and MP4
- [ ] Some form of Kepler <> pydeck integration
- [ ] Add support for a data legend (#4851)
- [ ] Display message if widget is not enabled
