### ISSUE TITLE
Checklist carto module for 8.5

### ISSUE THREAD

**Issue by alasarr** [visgl/deck.gl#5928]
Rename `CARTO cloud native` to `CARTO 3`:
- [x] Update documentation @borja-munoz 
- [x] Rename references in code @alasarr 

Other stuff:
- [x] Update scripting examples. @alasarr 
- [x] Replace the email link to access `CARTO 3` for a link to the website form. @borja-munoz 
- [x] Update https://docs.carto.com/deck-gl/overview/ with the new version. @borja-munoz 
- [x] Use always Authorization header to authenticate.  @alasarr

**Comment by alasarr** [comment]
All changes ready. We only need to merge [this PR](https://github.com/CartoDB/documentation/pull/118) when the release will be published in NPM
