### ISSUE TITLE
8.5 Release Tracker

### ISSUE THREAD

**Issue by Pessimistress** [visgl/deck.gl#5948]
Target release date TBD

- [x] Bump all dependencies (luma.gl, math.gl, probe.gl and loaders.gl) to latest release
- [x] Publish alpha/beta
- [x] Bump all examples to latest alpha/beta
- [x] Stage the website
- [x] Verify whats-new
- [x] Verify upgrade-guide
- [x] Verify all issues in milestone are closed or move out
- [x] Verify all API changes are documented
- [ ] Website (docs and example) testing: [staging](https://pessimistress.github.io/deck.gl/)
    - [x] Testing on Chrome
    - [x] Testing on Safari
    - [x] Testing on Firefox
    - [x] Testing on Edge
    - [x] Testing on iOS
    - [x] Testing on Android
- [x] Cut 8.5-release branch after all fixes
- [x] Update website doc urls to point to `8.5-release` branch
- [ ] Publish 8.5 prod version.

**Comment by Pessimistress** [comment]
Bug:
- [ ] Point cloud example: camera drifts while zooming

**Comment by felixpalmer** [comment]
Bug:

- [ ] Minimap not rendered in minimap example
- [ ] FirstPersonView example does not load

**Comment by ajduberstein** [comment]
[Playground](https://pessimistress.github.io/deck.gl/playground/) displays an error message over most visuals in its dropdown and seems to still depend on Mapbox tokens

**Comment by borja-munoz** [comment]
Bug (cc @felixpalmer):

- [ ] CartoLayer with vector tiles data source: The object in the picking info object is returning only the properties but not the geometry of the picked object

**Comment by Pessimistress** [comment]
@ibgreen Some of the examples are broken by a breaking change in `@loaders.gl/csv`. Because `type` is default to `'array-row-table'` the loader no longer returns object rows by default. I personally prefer to revert it to the old behavior (object row if header is true, array row otherwise). If this intentional, it should be added to the upgrade guide.

**Comment by Pessimistress** [comment]
@felixpalmer The FPV example is working, it's just the play button image that does not load (due to staging issues).

**Comment by ibgreen** [comment]
Yes, I was about to add more info on the new `shape` option into the docs. 

I am fine with changing the default `shape` to `object-row-table` rather than `array-row-table`, but I don't want the output "shape" to depend on the file. We generate default column names when header is not present so `object-row-table` should work for files that have no header.

**Comment by ibgreen** [comment]
https://github.com/visgl/loaders.gl/pull/1631

**Comment by alasarr** [comment]
I've just tested website in staging for Chrome, Firefox and Safari. Overall, it looks good, I've found only two issues:

- https://github.com/visgl/deck.gl/issues/5987 (only in chrome)
- https://github.com/visgl/deck.gl/issues/5986 (same error on all the environments)
