### ISSUE TITLE
pydeck next releases tracker

### ISSUE THREAD

**Issue by ajduberstein** [visgl/deck.gl#6142]
#### Updates

- [x] Lock to deck.gl 8.6
- [x] Release a version of pydeck where Jupyter is not in the dependencies

#### Tentative updates
- [ ] Support a selection layer (like nebula.gl's EditableGeoJsonLayer in kepler.gl)
- [ ] Default stylings
- [ ] Add support for bidirectional Google Colab integration
- [ ] Support for TileLayer
- [ ] Add within-browser support for playing data over time
- [ ] Support feature blending (e.g. dodge and burn blends)
- [ ] Export to image, GIF, and MP4
- [ ] Add support for a data legend (#4851)
- [ ] Display message if widget is not enabled

**Comment by ratnanil** [comment]
Will bidirectional integration also be available for streamlit? I've been looking forward to this ever since @ajduberstein's announcement [@JupyterCon2020](https://youtu.be/i-dGU80hNOw?t=1278) (see below)

![image](https://user-images.githubusercontent.com/12532091/200259515-c02b2bee-ef3b-4dc9-a046-e841095fa58e.png)
