### ISSUE TITLE
Tracker: Migrate to ocular-dev-tools v1

### ISSUE THREAD

**Issue by ibgreen** [visgl/deck.gl#6182]
#### Target Use case
- Enable full typescript support (.ts) 
- Benefit from tooling and configuration updates in latest ocular-dev-tools

#### Proposed feature
- Bump to ocular-dev-tools 1.0.0-alpha. 

#### Issues 
  - [x] Check build
  - [x] Check node tests
  - [ ] Check browser tests
  - [ ] Check pydeck
  - [ ] Check website
  - [ ] Check prettier settings (yarn lint fix will change a lot of code, mainly arrow functions)
