### ISSUE TITLE
8.6 Release Tracker

### ISSUE THREAD

**Issue by Pessimistress** [visgl/deck.gl#6266]
Target release date 10/12

- [ ] Publish alpha/beta
- [ ] Bump all examples to latest alpha/beta
- [ ] Stage the website
- [ ] Verify whats-new
- [ ] Verify upgrade-guide
- [ ] Verify all issues in milestone are closed or move out
- [ ] Verify all API changes are documented
- [ ] Website (docs and example) testing: 
    - [ ] Testing on Chrome
    - [ ] Testing on Safari
    - [ ] Testing on Firefox
    - [ ] Testing on Edge
    - [ ] Testing on iOS
    - [ ] Testing on Android
- [ ] Cut 8.6-release branch after all fixes
- [ ] Update website doc urls to point to `8.6-release` branch
- [ ] Publish 8.6 prod version.

**Comment by alasarr** [comment]
@AnaDiaz85 can you help us with the website testing?

**Comment by alasarr** [comment]
Staging available at https://alasarr.github.io/deck.gl

**Comment by AnaDiaz85** [comment]
I have already tested in Chrome, Firefox and Safari from my MAC laptop. (I am not able to check the markers since I am not a collaborater, I guess)

A common minor issue to all browsers is that the view https://alasarr.github.io/deck.gl/examples/first-person-view/ seems that it doesn't load the play button properly.
