### ISSUE TITLE
8.7 Release Tracker

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#6652]
Target release date 28/02

- [x] Publish alpha/beta
- [x] Bump all examples to latest alpha/beta @felixpalmer 
- [x] Stage the website @alasarr 
- [x] Verify whats-new @felixpalmer 
- [x] Verify upgrade-guide @felixpalmer 
- [ ] Verify all issues in milestone are closed or move out @alasarr 
- [x] Verify all API changes are documented @Pessimistress 
- [x] Website (docs and example) testing: @AnaDiaz85 
    - [x] Testing on Chrome
    - [x] Testing on Safari
    - [x] Testing on Firefox
    - [x] Testing on Edge
    - [x] Testing on iOS
    - [x] Testing on Android
- [x] Cut 8.7-release branch after all fixes
- [x] Update website doc urls to point to `8.7-release` branch
- [ ] Publish 8.7 prod version.

**Comment by alasarr** [comment]
Website available at https://alasarr.github.io/deck.gl

**Comment by AnaDiaz85** [comment]
QA: https://app.shortcut.com/cartoteam/story/211645/qa-deck-gl-8-7

@felixpalmer , @alasarr , in this ticket you can find the minor issues I found as well as the version used in each browser / mobile device

**Comment by alasarr** [comment]
>Integration with Google fails in Chrome, Safari, Firefox, Edge, IOS and Android
It's an issue with the API key and the referer. I'll fix it

>Views > FirstPersonView is missing the "play" icon in Google fails in Chrome, Safari, Firefox, Edge, IOS and Android

It's not important, it's a missing file in staging environment

**Comment by alasarr** [comment]
Google maps working in staging
