### ISSUE TITLE
Website v9 issue tracker

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#8193]
CLOSING IN FAVOUR OF: https://github.com/visgl/deck.gl/issues/7457

### Description

Tracker for issues on v9 staging website: https://felixpalmer.github.io/deck.gl

### Broken demos

- [ ] `examples/arcgis`
- [ ] `examples/carto` https://github.com/visgl/deck.gl/pull/8239
- [ ] `examples/heatmap-layer` https://github.com/visgl/deck.gl/pull/8307 https://github.com/visgl/deck.gl/issues/8317
- [ ] `examples/google-maps` https://github.com/visgl/deck.gl/issues/8302 https://github.com/visgl/deck.gl/issues/8420
- [ ] `examples/mapbox` https://github.com/visgl/deck.gl/issues/8237
- [ ] `examples/playground`

### Fixed

- [x] `docs/api-reference/layers/column-layer` https://github.com/visgl/deck.gl/issues/8219
- [x] `docs/api-reference/mesh-layers/scenegraph-layer` (Fixed by bump to loaders v4)
- [x] `examples/contour-layer` https://github.com/visgl/deck.gl/issues/8314
- [x] `examples/first-person-view` https://github.com/visgl/deck.gl/issues/8315
- [x] `examples/google-3d-tiles` https://github.com/visgl/deck.gl/issues/8316
- [x] `examples/orthographic-view` https://github.com/visgl/deck.gl/pull/8242
- [x] `examples/terrain-extension`
- [x] `examples/terrain-layer`
- [x] `examples/tile-3d-layer` https://github.com/visgl/deck.gl/issues/8316
- [x] `examples/geojson-layer-polygons` https://github.com/visgl/deck.gl/pull/8246
- [x] `examples/hexagon-layer`
- [x] `examples/scenegraph-layer` https://github.com/visgl/deck.gl/issues/8316
- [x] `examples/screen-grid-layer` https://github.com/visgl/deck.gl/issues/8318
- [x] `examples/text-layer` https://github.com/visgl/deck.gl/pull/8255
- [x] `examples/orbit-view` https://github.com/visgl/deck.gl/issues/8266
- [x] `examples/wms-layer` https://github.com/visgl/loaders.gl/pull/2799
- [x] `examples/collision-filter-extension` https://github.com/visgl/deck.gl/pull/8255

**Comment by estherluque** [comment]
**Broken maps** 

- [x] https://deck.gl/examples/contour-layer

**Steps**
1. Go to ContourLayer example https://deck.gl/examples/contour-layer

**Current result**
The layers don't appear (Isoband and Isoline) and the console shows an error
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 9 40 43" src="https://github.com/visgl/deck.gl/assets/50578158/b984df63-dec1-4685-8401-5816c5a2aa70">
[contourLayer:log+har.zip](https://github.com/visgl/deck.gl/files/13039540/contourLayer.log%2Bhar.zip)


**Expected result**
The layers appear
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 9 45 49" src="https://github.com/visgl/deck.gl/assets/50578158/a481b727-5e5f-4174-a999-29421ba7395e">

**Comment by estherluque** [comment]
**Broken maps** 

- [x] https://felixpalmer.github.io/deck.gl/examples/geojson-layer-polygons

**Steps**
1. Go to GeoJson Layer (Polygons) example https://felixpalmer.github.io/deck.gl/examples/geojson-layer-polygons

**Current result**
The 3D layer doesn't appear and the console shows an error
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 9 51 01" src="https://github.com/visgl/deck.gl/assets/50578158/7198af5a-eed8-4b69-a608-5088b76477d8">
[GeoJsonLayerPolygon:log+har.zip](https://github.com/visgl/deck.gl/files/13039614/GeoJsonLayerPolygon.log%2Bhar.zip)

**Expected result**
The 3D layer appears
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 9 55 01" src="https://github.com/visgl/deck.gl/assets/50578158/98a1171a-d855-4baa-b474-8eab5a92ea14">

**Comment by estherluque** [comment]
**Broken maps** 

- [x] https://felixpalmer.github.io/deck.gl/examples/heatmap-layer

**Steps**
1. Go to Heatmap Layer example https://felixpalmer.github.io/deck.gl/examples/heatmap-layer

**Current result**
The layers don't appear and the console shows an error
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 9 57 54" src="https://github.com/visgl/deck.gl/assets/50578158/ae0435e1-74f0-4205-b37b-454fd92c04db">
[HeatmapLayer:log+har.zip](https://github.com/visgl/deck.gl/files/13039676/HeatmapLayer.log%2Bhar.zip)

**Expected result**
The layers appear
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 9 58 27" src="https://github.com/visgl/deck.gl/assets/50578158/b54b1a17-61c2-4828-bcd1-8a0ad203bbf7">

**Comment by estherluque** [comment]
### Broken examples
- [ ] ContourLayer
- [ ] GeoJson Layer (Polygons)
- [ ] Heatmap Layer
- [ ] Hexagon Layer

**Comment by estherluque** [comment]
**Broken maps** 

- [ ] https://felixpalmer.github.io/deck.gl/examples/hexagon-layer

**Steps**
1. Go to Hexagon Layer example https://felixpalmer.github.io/deck.gl/examples/hexagon-layer

**Current result**
The layers don't appear and the console is empty
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 16 28 00" src="https://github.com/visgl/deck.gl/assets/50578158/4b05608d-93e9-4f3d-ace8-48e3c0bdcdf6">
[HexagonLayer:Log+har.zip](https://github.com/visgl/deck.gl/files/13043875/HexagonLayer.Log%2Bhar.zip)

**Expected result**
The layers appear
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 16 28 16" src="https://github.com/visgl/deck.gl/assets/50578158/e2f04652-a650-473a-b785-3a483c838570">

**Comment by estherluque** [comment]
**Broken maps** 

- [ ] https://felixpalmer.github.io/deck.gl/examples/point-cloud-layer

**Steps**
1. Go to PointCloudLayer example https://felixpalmer.github.io/deck.gl/examples/point-cloud-layer

**Current result**
The background color is different from https://deck.gl/examples/point-cloud-layer
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 16 47 10" src="https://github.com/visgl/deck.gl/assets/50578158/ecbcf903-3540-448f-b183-e17bfff76204">

**Expected result**
Real background color
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 16 49 27" src="https://github.com/visgl/deck.gl/assets/50578158/20440b5e-5ba1-417f-ab83-b55e3fd43020">

**Comment by estherluque** [comment]
**Broken maps** 

- [ ] https://felixpalmer.github.io/deck.gl/examples/scenegraph-layer

**Steps**
1. Go to ScenegraphLayer example https://felixpalmer.github.io/deck.gl/examples/scenegraph-layer

**Current result**
The layers don't appear and the console is empty
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 16 57 15" src="https://github.com/visgl/deck.gl/assets/50578158/7f796faa-476a-4a80-bb32-27011ec82141">
But this error appears after
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 16 56 55" src="https://github.com/visgl/deck.gl/assets/50578158/03b5e1a4-3026-4183-85a2-c72f6e68d8a7">
[ScenegrapghLayer.zip](https://github.com/visgl/deck.gl/files/13044242/ScenegrapghLayer.zip)

**Expected result**
The layers appear
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 17 02 16" src="https://github.com/visgl/deck.gl/assets/50578158/6930f06c-2487-4d0e-a269-f732cb62c2b4">

**Comment by estherluque** [comment]
**Broken maps** 

- [ ] https://felixpalmer.github.io/deck.gl/examples/screen-grid-layer

**Steps**
1. Go to ScreenGridLayer example https://felixpalmer.github.io/deck.gl/examples/screen-grid-layer

**Current result**
The layers don't appear and the console shows an error
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 17 04 20" src="https://github.com/visgl/deck.gl/assets/50578158/1a99a5fb-b566-4edc-a34d-67056c2b6995">
[ScreenGridLayer.zip](https://github.com/visgl/deck.gl/files/13044343/ScreenGridLayer.zip)

**Expected result**
The layers appear
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 17 08 10" src="https://github.com/visgl/deck.gl/assets/50578158/a7a29a62-fef1-4870-bfce-68f454ff0f53">

**Comment by estherluque** [comment]
**Broken maps** 

- [ ] https://felixpalmer.github.io/deck.gl/examples/text-layer

**Steps**
1. Go to TextLayer example https://felixpalmer.github.io/deck.gl/examples/text-layer

**Current result**
The map don't appear and the console is empty
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 17 12 38" src="https://github.com/visgl/deck.gl/assets/50578158/0d1f98b1-8d80-4df5-9ecb-df8e13d2aa0b">
[TextLayer:Log+Har.zip](https://github.com/visgl/deck.gl/files/13044396/TextLayer.Log%2BHar.zip)

**Expected result**
The map appear
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 17 13 02" src="https://github.com/visgl/deck.gl/assets/50578158/aa7ca6c0-230f-4af2-84f3-a5b281beda00">

**Comment by estherluque** [comment]
**Broken maps** 

- [ ] https://felixpalmer.github.io/deck.gl/examples/tile-3d-layer

**Steps**
1. Go to Tile3DLayer example https://felixpalmer.github.io/deck.gl/examples/tile-3d-layer

**Current result**
The map doesn't appear and the console is empty
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 17 21 16" src="https://github.com/visgl/deck.gl/assets/50578158/0b6740f2-ac82-4887-a319-cbc752594fa9">
[Tile3DLayer:Log+har.zip](https://github.com/visgl/deck.gl/files/13044483/Tile3DLayer.Log%2Bhar.zip)

**Expected result**
The map appears
<img width="1440" alt="Captura de pantalla 2023-10-19 a las 17 23 40" src="https://github.com/visgl/deck.gl/assets/50578158/a0d04aa4-f662-464f-ab4f-1302a6995f66">

**Comment by estherluque** [comment]
**Broken maps** 

- [ ] https://felixpalmer.github.io/deck.gl/examples/google-3d-tiles

**Steps**
1. Go to Google 3D Layer example https://felixpalmer.github.io/deck.gl/examples/google-3d-tiles

**Current result**
The layers don't appear and the console is empty
<img width="1440" alt="Captura de pantalla 2023-10-20 a las 10 02 24" src="https://github.com/visgl/deck.gl/assets/50578158/8b402b58-ef08-4782-b5d5-a9fcbc9a9519">
[Google3DTiles:Log+Har.zip](https://github.com/visgl/deck.gl/files/13051766/Google3DTiles.Log%2BHar.zip)

**Expected result**
The layers appear
<img width="1440" alt="Captura de pantalla 2023-10-20 a las 10 03 12" src="https://github.com/visgl/deck.gl/assets/50578158/d76ad62e-1813-4ab1-80db-da2194d9f577">

**Comment by estherluque** [comment]
**Broken maps** 

- [ ] https://felixpalmer.github.io/deck.gl/examples/google-maps

**Steps**
1. Go to GoogleMaps example https://felixpalmer.github.io/deck.gl/examples/google-maps

**Current result**
The map doesn't appear and the console shows this error
<img width="1439" alt="Captura de pantalla 2023-10-20 a las 10 28 31" src="https://github.com/visgl/deck.gl/assets/50578158/39809a99-acc4-4b74-813d-267928ce4a00">
[GoogleMaps:Log+Har.zip](https://github.com/visgl/deck.gl/files/13052018/GoogleMaps.Log%2BHar.zip)

**Expected result**
The map appears
<img width="1440" alt="Captura de pantalla 2023-10-20 a las 10 29 08" src="https://github.com/visgl/deck.gl/assets/50578158/f6a085f3-6323-47c4-822e-a274359fb786">

**Comment by estherluque** [comment]
**Broken maps** 

- [ ] https://felixpalmer.github.io/deck.gl/examples/mapbox

**Steps**
1. Go to Mapbox example https://felixpalmer.github.io/deck.gl/examples/mapbox

**Current result**
The map appears at the bottom and the console shows this error
<img width="1440" alt="Captura de pantalla 2023-10-20 a las 10 32 36" src="https://github.com/visgl/deck.gl/assets/50578158/ec44bca1-8f81-4c09-8cee-08860152151c">
[Mapbox:Log+Har.zip](https://github.com/visgl/deck.gl/files/13052064/Mapbox.Log%2BHar.zip)

**Expected result**
The map appears correctly
<img width="1440" alt="Captura de pantalla 2023-10-20 a las 10 33 29" src="https://github.com/visgl/deck.gl/assets/50578158/8ea4e33d-425d-45f1-a7e5-17ad661d54df">

**Comment by estherluque** [comment]
**Broken maps** 

- [ ] https://felixpalmer.github.io/deck.gl/examples/plot

**Steps**
1. Go to OrbitView example https://felixpalmer.github.io/deck.gl/examples/plot

**Current result**
The map doesn't appear and the console is empty
<img width="1440" alt="Captura de pantalla 2023-10-20 a las 10 48 30" src="https://github.com/visgl/deck.gl/assets/50578158/8d3b4e2e-8fd0-4686-bca9-93fe640a5124">
[OrbitView:Log+Har.zip](https://github.com/visgl/deck.gl/files/13052288/OrbitView.Log%2BHar.zip)

**Expected result**
The map appears
<img width="1440" alt="Captura de pantalla 2023-10-20 a las 10 48 39" src="https://github.com/visgl/deck.gl/assets/50578158/3ee0f544-c024-478d-ba41-89db3931951b">

**Comment by estherluque** [comment]
**Broken maps** 

- [ ] https://felixpalmer.github.io/deck.gl/examples/orthographic-view

**Steps**
1. Go to OrthographicView example https://felixpalmer.github.io/deck.gl/examples/orthographic-view

**Current result**
The layers don't appear and the console is empty
<img width="1440" alt="Captura de pantalla 2023-10-20 a las 10 52 27" src="https://github.com/visgl/deck.gl/assets/50578158/8e1a96c2-2efc-4b50-b813-2d97ce241013">
[OrthographicView:Log+Har.zip](https://github.com/visgl/deck.gl/files/13052365/OrthographicView.Log%2BHar.zip)


**Expected result**
The layers appear
<img width="1440" alt="Captura de pantalla 2023-10-20 a las 10 53 23" src="https://github.com/visgl/deck.gl/assets/50578158/543c4214-ca4c-414c-98e7-e65159a11269">

**Comment by estherluque** [comment]
**Broken maps** 

- [ ] https://felixpalmer.github.io/deck.gl/examples/first-person-view

**Steps**
1. Go to FirstPersonView example https://felixpalmer.github.io/deck.gl/examples/first-person-view

**Current result**
The video is seen but not heard
<img width="1440" alt="Captura de pantalla 2023-10-20 a las 10 57 42" src="https://github.com/visgl/deck.gl/assets/50578158/e4f6f69b-d758-4660-be88-a1a1c010114a">
[FirstPersonView:Log+Har.zip](https://github.com/visgl/deck.gl/files/13052421/FirstPersonView.Log%2BHar.zip)

**Expected result**
The video is seen and heard

**Comment by estherluque** [comment]
**Broken maps** 

- [ ] https://felixpalmer.github.io/deck.gl/examples/collision-filter-extension

**Steps**
1. Go to CollisionFilterExtension example https://felixpalmer.github.io/deck.gl/examples/collision-filter-extension

**Current result**
The map doesn't appear and the console is empty
<img width="1440" alt="Captura de pantalla 2023-10-20 a las 11 09 37" src="https://github.com/visgl/deck.gl/assets/50578158/35726f13-c4be-4b14-b7f3-4f87ca827f15">
[CollisionFilterExtension:Log+Har.zip](https://github.com/visgl/deck.gl/files/13052493/CollisionFilterExtension.Log%2BHar.zip)

**Expected result**
The map appears
<img width="1440" alt="Captura de pantalla 2023-10-20 a las 11 10 11" src="https://github.com/visgl/deck.gl/assets/50578158/d6b3aba4-837e-4f38-bab0-917042b42d74">

**Comment by estherluque** [comment]
**Broken maps** 

- [ ] https://felixpalmer.github.io/deck.gl/examples/terrain-extension

**Steps**
1. Go to TerrainExtension example https://felixpalmer.github.io/deck.gl/examples/terrain-extension

**Current result**
The layers don't appear and the console is empty
<img width="1437" alt="Captura de pantalla 2023-10-20 a las 11 13 39" src="https://github.com/visgl/deck.gl/assets/50578158/a657ed08-098c-41c2-8462-1d3c068cc3f1">
[TerrainExtension:Log+Har.zip](https://github.com/visgl/deck.gl/files/13052531/TerrainExtension.Log%2BHar.zip)

**Expected result**
The layers appear
<img width="1440" alt="Captura de pantalla 2023-10-20 a las 11 13 42" src="https://github.com/visgl/deck.gl/assets/50578158/26f24726-e0a6-46f9-be5d-b0756b3d3f02">

**Comment by estherluque** [comment]
**Broken maps** 

- [ ] https://felixpalmer.github.io/deck.gl/docs/api-reference/layers/column-layer

**Steps**
1. Go to api-reference/layers/column-layer doc https://felixpalmer.github.io/deck.gl/docs/api-reference/layers/column-layer

**Current result**
The layers doesn't appear and the console is empty
<img width="1051" alt="Captura de pantalla 2023-10-20 a las 11 51 10" src="https://github.com/visgl/deck.gl/assets/50578158/a935897b-15d0-4763-8d62-39004b6e2b16">


**Expected result**
The layer appear
<img width="1139" alt="Captura de pantalla 2023-10-20 a las 11 51 32" src="https://github.com/visgl/deck.gl/assets/50578158/3208250d-6dfe-484e-8367-20d5d0dda34e">

**Comment by MariaB16** [comment]
### Broken examples
- [ ] ContourLayer https://deck.gl/examples/contour-layer > Google Chrome V.119.0.6045.123
- [ ] HeatmapLayer https://felixpalmer.github.io/deck.gl/examples/heatmap-layer > Google Chrome V.119.0.6045.123
-GPUGridLayer (WebGL2) (https://felixpalmer.github.io/deck.gl/docs/api-reference/aggregation-layers/gpu-grid-layer).
HeatmapLayer (https://felixpalmer.github.io/deck.gl/docs/api-reference/aggregation-layers/heatmap-layer)

**Comment by MariaB16** [comment]
FIREFOX
BROKEN DOCS 

- [ ]  About 64-bit Layers (https://felixpalmer.github.io/deck.gl/docs/developer-guide/fp64) > The color range looks different in firefox than in chrome. 
- [ ]  BitmapLayer (https://felixpalmer.github.io/deck.gl/docs/api-reference/layers/bitmap-layer) > The color range is more intense than chrome.
- [ ]  SL2Layer (https://felixpalmer.github.io/deck.gl/docs/api-reference/geo-layers/s2-layer) <The color range is more intense than chrome. 
- [ ]  ScatterplotLayer (https://felixpalmer.github.io/deck.gl/docs/api-reference/layers/scatterplot-layer) > The color is more intense than chrome. 
- [ ] OrthographicView (https://felixpalmer.github.io/deck.gl/docs/api-reference/core/orthographic-view) > The color is more intense than chrome. 
- [ ]  PostProcessEffect (https://felixpalmer.github.io/deck.gl/docs/api-reference/core/post-process-effect) > The color is more intense than chrome.

**Comment by MariaB16** [comment]
FIREFOX 

- [ ]  GeohashLayer (https://felixpalmer.github.io/deck.gl/docs/api-reference/geo-layers/geohash-layer) > Color palette is more intense than example in chrome.

**Comment by MariaB16** [comment]
GOOGLE CHROME Versión 119.0.6045.123
Broken Docs

- [ ]  Contourlayer (https://felixpalmer.github.io/deck.gl/docs/api-reference/aggregation-layers/contour-layer)

- [ ]  GPUGridLayer (WebGL2) (https://felixpalmer.github.io/deck.gl/docs/api-reference/aggregation-layers/gpu-grid-layer)

- [ ]  HeatmapLayer (https://felixpalmer.github.io/deck.gl/docs/api-reference/aggregation-layers/heatmap-layer)

- [ ]  WMSLayer (Experimental) (https://felixpalmer.github.io/deck.gl/docs/api-reference/geo-layers/wms-layer)

 

- [ ] ScenegraphLayer (https://felixpalmer.github.io/deck.gl/docs/api-reference/mesh-layers/scenegraph-layer)

- [ ]  ScreenGridLayer (https://felixpalmer.github.io/deck.gl/docs/api-reference/aggregation-layers/screen-grid-layer)
SAFARI
BROKEN DOCS
- [ ]  About 64-bit Layers (https://felixpalmer.github.io/deck.gl/docs/developer-guide/fp64) > The color range looks different in firefox than in chrome.

- [ ]  BitmapLayer (https://felixpalmer.github.io/deck.gl/docs/api-reference/layers/bitmap-layer) > The color range is more intense than chrome.

- [ ]  SL2Layer (https://felixpalmer.github.io/deck.gl/docs/api-reference/geo-layers/s2-layer) <The color range is more intense than chrome.

- [ ]  ScatterplotLayer (https://felixpalmer.github.io/deck.gl/docs/api-reference/layers/scatterplot-layer) > The color is more intense than chrome.
- [ ] OrthographicView (https://felixpalmer.github.io/deck.gl/docs/api-reference/core/orthographic-view) > The color is more intense than chrome.

- [ ]  PostProcessEffect (https://felixpalmer.github.io/deck.gl/docs/api-reference/core/post-process-effect) > The color is more intense than chrome.
FIREFOX
- [ ] GeohashLayer (https://felixpalmer.github.io/deck.gl/docs/api-reference/geo-layers/geohash-layer) > Color palette is more intense than example in chrome.
