### ISSUE TITLE
[Tracker] @deck.gl/mapbox v9

### ISSUE THREAD

**Issue by chrisgervang** [visgl/deck.gl#8541]
### Description

I've spent some time trying to work out doc and example updates for [deck + mapbox](https://deck.gl/docs/developer-guide/base-maps/using-with-mapbox) in v9 (and ecosystem... react-map-gl v5 → v7, maplibre, and mapbox).

There are a couple items I'd like to discuss:

- [ ] New docs [in this PR](https://github.com/visgl/deck.gl/pull/8146#discussion_r1501118305).
  - Highlights: New [recommendations](https://github.com/visgl/deck.gl/pull/8146/files#diff-f87533d9a3d02ac2e8fd54b985f1c3d9f77ea98d57137a4cd63b249ff483cad3R9-R13), WebGL2 [interleave compatibility](https://github.com/visgl/deck.gl/pull/8146/files#diff-cf26456e6120307c2e3dadaffc9cf0d7696a0c97a577c810a33000bd59f42a8bR63-R71) notes.
- [ ] Adopt MapboxOverlay in our getting started with react+mapbox example (merge [#8181](https://github.com/visgl/deck.gl/pull/8181)).
  - This makes <Map> the parent. We previously recommended using <DeckGL> as the parent, but this no longer supports controls/plugins in react-map-gl v7.
- [ ] Replace MapboxLayer with an interleaved MapboxOverlay in our [safegraph](https://deck.gl/examples/mapbox) example
- [ ] Nit: Rename safegraph example to mapbox-interleaved (or similar) [#8522](https://github.com/visgl/deck.gl/issues/8522)
- [ ] Add a pure-js interleaved MapboxOverlay example somewhere. I think the [galley](https://github.com/visgl/deck.gl/tree/master/examples/gallery/src) makes sense.
### Discussion
- [ ] Formally deprecating MapboxLayer (should we? when? why not?)
- [ ] Drop examples and support for mapbox-gl v1 (should we? when? why not?)
  - Compatibility is slowly dropping.. it will always be WebGL1, which means deck can no longer share a rendering context.
  - Maplibre is the future, right?
