### ISSUE TITLE
Tracker: Restoring unit tests

### ISSUE THREAD

**Issue by donmccurdy** [visgl/deck.gl#8592]
### Target Use Case

Currently we have a number of unit tests disabled. Individual test cases are disabled with `test.skip(...)`, or files containing tests are commented out from the `index.ts` entrypoint. As we're getting closer to a v9 release, I thought it might be helpful to list all of these, in case any feel important to restore before a stable release. 

Optionally, perhaps it would also be worth going through and un-commenting all the imports, fixing any compilation errors, and adding `test.skip` as needed until we're able to fix the unit tests properly.

## Disabled test files

```bash
grep -Rnw "test" -e "// import" --include "index.ts"
```

- [ ] test/modules/carto
- [ ] test/modules/extensions
- [ ] test/modules/geo-layers
- [ ] test/modules/jupyter-widget
- [ ] test/modules/mapbox
- [ ] test/modules/react
- [ ] test/modules/core/utils/compare-objects.spec
- [ ] test/modules/core/lib/layer.spec
- [ ] test/modules/core/lib/composite-layer.spec
- [ ] test/modules/core/lib/layer-extension.spec
- [ ] test/modules/core/lib/layer-manager.spec
- [ ] test/modules/core/lib/tooltip.spec
- [ ] test/modules/core/lib/transition-manager.spec
- [ ] test/modules/core/lib/uniform-transition-manager.spec
- [ ] test/modules/core/lib/effect-manager.spec
- [ ] test/modules/core/lib/pick-layers.spec
- [ ] test/modules/core/lib/picking.spec
- [ ] test/modules/core/lib/view-manager.spec
- [ ] test/modules/core/lib/widget-manager.spec
- [ ] test/modules/layers/bitmap-layer.spec
- [ ] test/modules/layers/path-tesselator.spec
- [ ] test/modules/layers/polygon-tesselation.spec
- [ ] test/modules/layers/core-layers.spec
- [ ] test/modules/layers/polygon-layer.spec
- [ ] test/modules/layers/geojson.spec
- [ ] test/modules/layers/geojson-layer.spec
- [ ] test/modules/layers/geojson-binary.spec
- [ ] test/modules/layers/point-cloud-layer.spec
- [ ] test/modules/layers/path-layer/path-layer-vertex.spec
- [ ] test/modules/layers/text-layer/text-layer.spec
- [ ] test/modules/layers/column-geometry.spec
- [ ] test/modules/layers/scatterplot-layer.spec
- [ ] test/modules/geo-layers/tileset-2d/tileset-2d.spec
- [ ] test/modules/extensions/terrain/terrain-effect.spec
- [ ] test/modules/extensions/terrain/terrain.spec
- [ ] test/modules/carto/api/parseMap.spec
- [ ] test/modules/carto/layers/vector-tile-layer.spec
- [ ] test/modules/aggregation-layers/contour-layer/contour-layer.spec
- [ ] test/modules/aggregation-layers/cpu-grid-layer/cpu-grid-layer.spec
- [ ] test/modules/aggregation-layers/gpu-cpu-aggregator.spec
- [ ] test/modules/aggregation-layers/gpu-grid-layer/gpu-grid-cell-layer-vertex.spec
- [ ] test/modules/aggregation-layers/gpu-grid-layer/gpu-grid-cell-layer.spec
- [ ] test/modules/aggregation-layers/gpu-grid-layer/gpu-grid-layer.spec
- [ ] test/modules/aggregation-layers/grid-aggregation-layer.spec
- [ ] test/modules/aggregation-layers/grid-layer.spec
- [ ] test/modules/aggregation-layers/heatmap-layer/heatmap-layer.spec
- [ ] test/modules/aggregation-layers/hexagon-layer.spec
- [ ] test/modules/aggregation-layers/screen-grid-layer.spec
- [ ] test/modules/aggregation-layers/screengrid-cell-layer.spec
- [ ] test/modules/aggregation-layers/utils/gpu-grid-aggregator.spec
- [ ] test/modules/mesh-layers/simple-mesh-layer.spec
- [ ] test/modules/mesh-layers/scenegraph-layer.spec

## Disabled test cases

```bash
grep -Rnw "test" -e "test.skip" --include "*.spec.ts"
```

- [ ] `test/modules/core/passes/pick-layers-pass.spec.ts` → PickLayersPass#drawPickingBuffer
- [ ] `test/modules/core/lib/deck.spec.ts` → Deck#rendering, picking, logging
- [ ] `test/modules/core/lib/attribute/attribute.spec.ts` → Attribute#allocate - partial
- [ ] `test/modules/core/lib/attribute/attribute.spec.ts` → Attribute#updateBuffer
- [ ] `test/modules/core/lib/deck-picker.spec.ts` → DeckPicker#pick empty
- [ ] `test/modules/core/effects/post-process-effect.spec.ts` → PostProcessEffect#postRender
- [ ] `test/modules/core/shaderlib/project/project-32-64-glsl.spec.ts` → project32&64#vs
- [ ] `test/modules/core/shaderlib/project/project-glsl.spec.ts` → project#vs
- [ ] `test/modules/google-maps/google-maps-overlay.spec.ts` → GoogleMapsOverlay#style
- [ ] `test/modules/geo-layers/h3-layers.spec.ts` → H3HexagonLayer
- [ ] `test/modules/geo-layers/h3-layers.spec.ts` → H3HexagonLayer#_shouldUseHighPrecision
- [ ] `test/modules/geo-layers/h3-layers.spec.ts` → H3HexagonLayer#viewportUpdate
- [ ] `test/modules/geo-layers/wms-layer.spec.ts` → WMSLayer', async t => {
- [ ] `test/modules/carto/layers/raster-tile-layer.spec.ts` → RasterLayer
- [ ] `test/modules/aggregation-layers/utils/gpu-grid-aggregator.spec.ts` → GPUGridAggregator#GPU
- [ ] `test/modules/aggregation-layers/gpu-cpu-aggregator.spec.ts` → Aggregation#ScreenSpace
- [ ] `test/modules/aggregation-layers/gpu-cpu-aggregator.spec.ts` → Aggregation#WorldSpace

**Comment by Pessimistress** [comment]
Majority of the layer tests can be restored once luma is update to >=beta.7
