### ISSUE TITLE
Tracker: v9.1

### ISSUE THREAD

**Issue by ibgreen** [visgl/deck.gl#9056]
## v9.1

- Target Release Date: Q3 2024
- Follows [v9.0 Tracker](https://github.com/visgl/deck.gl/issues/7457), Followed by  [v9.2 Tracker](https://github.com/visgl/deck.gl/issues/9172)
- See [luma.gl v9.1 Tracker](https://github.com/visgl/luma.gl/issues/1946)

### Chores

- [x] Lock 9.0-release to `luma.gl@~9.0.0` @ibgreen 
- [x] Publish staging website @felixpalmer 
  - [x] https://github.com/visgl/deck.gl/pull/9280
  - [x] https://github.com/visgl/deck.gl/pull/9281
  - [x] https://github.com/visgl/deck.gl/pull/9282
- [ ] Replace react-map-gl v5 with v7 in examples and use maplibre

### Prepare for WebGPU

- Note: `device.readPixelsWebGL()` is still supported, will be removed in luma.gl 9.2.
- [x] Replace calls to `device.clearWebGL()` (requires creating new renderpasses with clearColor, clearDepth parameters)
- [x] Replace calls to `device.updateModuleSettingsWebGL()`
- [x] Replace calls to `device.setParametersWebGL()`
- [x] Replace calls to `device.withParametersWebGL()`
- [x] Replace `GL.TRIANGLE_FAN` topology / draw modes (not supported by webgpu) 
- [x] Update picking module in Layers to use`ShaderInputs` from luma @felixpalmer 
- [x] Update all layers/extensions/... to use UniformBuffers @felixpalmer 
- [x] Port all shaders to GLSL 3.00 @donmccurdy 

### Widgets in React and pydeck

- [x] https://github.com/visgl/deck.gl/pull/9278 @chrisgervang 
- [x] https://github.com/visgl/deck.gl/pull/9309 @chrisgervang 
- [ ] https://github.com/visgl/deck.gl/pull/9304 @chrisgervang
- [x] https://github.com/visgl/deck.gl/pull/8991 @chrisgervang
- [x] https://github.com/visgl/deck.gl/pull/9303 @chrisgervang 
- [x] https://github.com/visgl/deck.gl/pull/9308 @chrisgervang
- [x] https://github.com/visgl/deck.gl/pull/9312
- [x] https://github.com/visgl/deck.gl/pull/9314
- [x] https://github.com/visgl/deck.gl/pull/9315
- [x] https://github.com/visgl/deck.gl/pull/9316
- [x] https://github.com/visgl/deck.gl/pull/9361

#### Bugs/PRs needed for release

- [ ] https://github.com/visgl/deck.gl/pull/9200 @Pessimistress 
- [x] https://github.com/visgl/deck.gl/issues/8314 - Working, but only with GPU aggregation disabled
- [x] https://github.com/visgl/deck.gl/issues/8318 - Working, but only with GPU aggregation disabled
- [x] https://github.com/visgl/deck.gl/issues/8321
- [x] https://github.com/visgl/luma.gl/issues/2292
- [x] https://github.com/visgl/mjolnir.js/pull/8 @Pessimistress 
- [x] https://github.com/visgl/deck.gl/pull/9232 @donmccurdy 
- [x] https://github.com/visgl/deck.gl/pull/9209 @felixpalmer 
- [x] https://github.com/visgl/deck.gl/pull/9201 @Pessimistress 
- [x] Hide console warnings `Module XXX not found` @felixpalmer https://github.com/visgl/deck.gl/pull/9345
- [ ] https://github.com/visgl/deck.gl/pull/8731 @Pessimistress 

### Broken website pages/examples:

- [ ] https://felixpalmer.github.io/deck.gl/examples/first-person-view https://github.com/visgl/luma.gl/issues/2304
- [x] https://felixpalmer.github.io/deck.gl/examples/arcgis https://github.com/visgl/deck.gl/pull/9341
- [x] https://felixpalmer.github.io/deck.gl/examples/multi-view https://github.com/visgl/deck.gl/pull/9338
- [x] https://felixpalmer.github.io/deck.gl/examples/mapbox https://github.com/visgl/deck.gl/pull/9296
- [x] https://felixpalmer.github.io/deck.gl/examples/mask-extension https://github.com/visgl/deck.gl/pull/9339
- [x] https://felixpalmer.github.io/deck.gl/playground https://github.com/visgl/deck.gl/pull/9340
- [x] https://felixpalmer.github.io/deck.gl/examples/globe-view https://github.com/visgl/deck.gl/pull/9306
- [x] https://felixpalmer.github.io/deck.gl/examples/plot https://github.com/visgl/deck.gl/pull/9307

### Clean up / remove deprecations etc

- [x] https://github.com/visgl/deck.gl/pull/9301

**Comment by Pessimistress** [comment]
- [ ] Lock 9.0-release to `luma.gl@~9.0.0`

**Comment by gdnwr** [comment]
Fix the following bugs in version V9.1.
https://github.com/visgl/deck.gl/issues/8818

**Comment by ibgreen** [comment]
> Fix the following bugs in version V9.1.

While it would indeed be great to get a fix, and I understand that you are trying your best to raise attention, this is not a regression in 9.1, so we wouldn't hold the release for that issue.

**Comment by Pessimistress** [comment]
Interleaved context use case is crashing due to

```
Error: WebGLDevice requires props.createCanvasContext to be set
    at new WebGLDevice (webgl-device.ts:116:13)
    at WebGLAdapter.attach (webgl-adapter.ts:55:12)
    at new Deck (deck.ts:371:39)
```

Reproduce steps:
- On master, navigate to examples/get-started/pure-js/maplibre
- In app.js, uncomment `interleaved: true`
- yarn && yarn start-local
