### ISSUE TITLE
Tracker: GlobeView graduation

### ISSUE THREAD

**Issue by Pessimistress** [visgl/deck.gl#9199]
### Target Use Case

This issue tracks TODO items in order to move GlobeView from experimental to a production feature.

### Proposal

Essential:

- [ ] Align Globe common space and camera parameters with maplibre-gl v5
- [ ] MapboxOverlay supports Maplibre's globe projection
- [ ] Align path/polygon subdivision scheme with maplibre-gl v5, or at lease in a way without apparent visual discrepancy
  + https://github.com/visgl/deck.gl/issues/7104
  + https://github.com/visgl/deck.gl/issues/6088

Good to have:
- [ ] Support rotation (bearing) in GlobeController
- [ ] Generic attribute subdivision
  + https://github.com/visgl/deck.gl/issues/5631

**Comment by charlieforward9** [comment]
https://github.com/user-attachments/assets/53d8dfe0-7835-4c10-ba11-86c921a8ac1c

In my implementation, simply adding `projection={"globe"}` to the `<Map>` component results in some of my layers disappearing (not all of them). Am I missing something simple or is this a bigger bug requiring a reproduction?

**Comment by charlieforward9** [comment]
More specifically, all my deck.gl layers show up except the `IconLayer`, I am working on figuring why out now.
